// Export formats and the shareable URL hash. Pure string work, no SDK import.
const isBN = v => v && typeof v === 'object' && Array.isArray(v.words) && 'negative' in v
const plain = v => isBN(v) ? v.toString(10) : Array.isArray(v) ? v.map(plain)
  : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, plain(x)])) : v

export const configJson = config => JSON.stringify(plain(config), null, 2)

export function inventJsonc(inp, params) {
  const { initialMarketCap, migrationMarketCap, liquidityWeights, ...rest } = params
  const dbcConfig = { buildCurveMode: inp.shape === 'constant' ? 1 : 3, initialMarketCap, migrationMarketCap,
    ...(liquidityWeights ? { liquidityWeights } : {}), ...rest,
    leftoverReceiver: 'YOUR_LEFTOVER_RECEIVER_ADDRESS', feeClaimer: 'YOUR_FEE_CLAIMER_ADDRESS' }
  const file = { rpcUrl: 'https://api.devnet.solana.com', dryRun: true, keypairFilePath: './keypair.json',
    computeUnitPriceMicroLamports: 100000, quoteMint: 'So11111111111111111111111111111111111111112', dbcConfig }
  return `// Generated by Curve Lab. Save as meteora-invent studio/config/dbc_config.jsonc, then: pnpm studio dbc-create-config\n${JSON.stringify(file, null, 2)}\n`
}

export function tsSnippet(inp, params) {
  const fn = inp.shape === 'constant' ? 'buildCurveWithMarketCap' : 'buildCurveWithLiquidityWeights'
  return `import { ${fn}, DynamicBondingCurveClient } from '@meteora-ag/dynamic-bonding-curve-sdk'
import { Connection, Keypair, PublicKey } from '@solana/web3.js'

const config = ${fn}(${JSON.stringify(params, null, 2)})
const client = new DynamicBondingCurveClient(new Connection('https://api.devnet.solana.com'), 'confirmed')
const configKp = Keypair.generate()
const wallet = new PublicKey('YOUR_WALLET_ADDRESS')
const tx = await client.partner.createConfig({ ...config, config: configKp.publicKey, payer: wallet,
  feeClaimer: wallet, leftoverReceiver: wallet, quoteMint: new PublicKey('So11111111111111111111111111111111111111112') })
// set tx.feePayer and tx.recentBlockhash, sign with the wallet and configKp, send
`
}

export const encodeHash = inp => '#c=' + encodeURIComponent(JSON.stringify(inp))

// -> inputs object, or null if the hash is missing or unreadable.
export function decodeHash(hash) {
  if (!hash.startsWith('#c=')) return null
  try { const v = JSON.parse(decodeURIComponent(hash.slice(3))); return v && typeof v === 'object' ? v : null }
  catch { return null }
}
